export const quotes = {
	Dot: [
		"The journey of a thousand miles begins with one step. - Lao Tzu",
		"The beginning is always today. - Mary Wollstonecraft Shelley",
		"The secret of getting ahead is getting started. - Mark Twain",
		"The way to get started is to quit talking and begin doing. - Walt Disney",
		"It does not matter how slowly you go as long as you do not stop. - Confucius",
		"Do not wait until the conditions are perfect to begin. Beginning makes the conditions perfect. - Alan Cohen",
		"You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
		"Beginnings are always messy. - John Galsworthy",
		"There will come a time when you believe everything is finished. That will be the beginning. - Louis L'Amour",
		"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
		"The beginning is the most important part of the work. - Plato",
		"The beginning of wisdom is the definition of terms. - Socrates",
		"Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
		"The beginning is always the hardest. - Unknown",
		"Every new beginning comes from some other beginning's end. - Seneca",
		"The beginnings and endings of all human undertakings are untidy. - John Galsworthy",
		"The person who removes a mountain begins by carrying away small stones. - Chinese Proverb",
		"The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
		"Success is not in what you have, but who you are. - Bo Bennett",
		"Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
	],
	Line: [
		"The line of life is a ragged diagonal between duty and desire. - William R. Alger",
		"In the middle of every difficulty lies opportunity. - Albert Einstein",
		"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
		"It always seems impossible until it's done. - Nelson Mandela",
		"The key to success is action, and the essential in action is perseverance. - Sun Yat-sen",
		"Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
		"Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
		"Success is the result of perfection, hard work, learning from failure, loyalty, and persistence. - Colin Powell",
		"The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
		"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do. - Pele",
		"With ordinary talent and extraordinary perseverance, all things are attainable. - Thomas Fowell Buxton",
		"The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
		"It's not whether you get knocked down; it's whether you get up. - Vince Lombardi",
		"A winner is just a loser who tried one more time. - George M. Moore Jr.",
		"Perseverance is failing 19 times and succeeding the 20th. - Julie Andrews",
		"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
		"A smooth sea never made a skilled sailor. - Franklin D. Roosevelt",
		"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
		"Fall seven times, stand up eight. - Japanese Proverb",
		"Perseverance is stubbornness with a purpose. - Josh Shipp",
	],
	Triangle: [
		"The will to endure is often the difference between failure and success. - David Sarnoff",
		"Endurance is not just the ability to bear a difficult thing, but to turn it into glory. - William Barclay",
		"The key to success is to focus our conscious mind on things we desire, not things we fear. - Brian Tracy",
		"We may encounter many defeats, but we must not be defeated. - Maya Angelou",
		"The only thing that overcomes hard luck is hard work. - Harry Golden",
		"Challenges are what make life interesting, and overcoming them is what makes life meaningful. - Joshua J. Marine",
		"To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
		"The harder the conflict, the more glorious the triumph. - Thomas Paine",
		"The only place where success comes before work is in the dictionary. - Vidal Sassoon",
		"Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
		"There is no failure except in no longer trying. - Elbert Hubbard",
		"I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
		"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
		"Success is not in what you have, but who you are. - Bo Bennett",
		"The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
		"I don't know the key to success, but the key to failure is trying to please everybody. - Bill Cosby",
		"Success is most often achieved by those who don't know that failure is inevitable. - Coco Chanel",
		"The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
		"Don't let what you cannot do interfere with what you can do. - John R. Wooden",
		"You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
	],
	Diamond: [
		"Diamonds are nothing more than chunks of coal that stuck to their jobs. - Malcolm Forbes",
		"Diamonds are intrinsically worthless, except for the deep psychological need they fill. - De Beers",
		"The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
		"Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
		"The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
		"Success is not just about making money. It's about making a difference. - Unknown",
		"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
		"Opportunities don't happen. You create them. - Chris Grosser",
		"I never dreamed about success, I worked for it. - Estee Lauder",
		"Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit. - Conrad Hilton",
		"Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
		"Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
		"The key to success is to start before you are ready. - Marie Forleo",
		"Success is not in what you have, but who you are. - Bo Bennett",
		"The difference between successful people and very successful people is that very successful people say no to almost everything. - Warren Buffett",
		"Don't watch the clock; do what it does. Keep going. - Sam Levenson",
		"Stop chasing the money and start chasing the passion. - Tony Hsieh",
		"Success is not just about making money. It's about making a difference. - Unknown",
		"Your success and happiness lie in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties. - Helen Keller",
		"I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
	],
};
